In [1]:
import numpy as np

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')



In [2]:
a = np.array(iris)
#extract column 'species'
a[:,4]


array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-versicolor',
       b'Iris-versicolor', b'Iris-versicolor', b'Iris-versicolor',
       b'Iris-versicol

In [3]:
a2d_f = np.array(a[:,0:4] , dtype='float')
#convert the first 4 columns to an 2D array
a2d_f



array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [4]:
np.mean(a2d_f[:,0])


5.843333333333334

In [5]:
np.median(a2d_f[:,0])


5.8

In [6]:
np.std(a2d_f[:,0])


0.8253012917851409

In [7]:
a2d_f.shape


(150, 4)

In [8]:
np.put(a2d_f, np.random.choice(range(150*4), 20, replace=False), np.nan)
#insert 20 values nan in the first column 
a2d_f

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, nan, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, nan, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, nan],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, nan],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [10]:
a1 = a2d_f[:,0] 
#Find the positions of the inserted np.nan values in the 1st column
np.where(np.isnan(a1))


(array([ 54,  71, 114, 122, 135, 148], dtype=int64),)

In [11]:
a2d_f[(a2d_f[:,2] > 1.5) & (a2d_f[:,0] < 5)]
#Filter the array by condition of the value in the 3rd column> 1.5 and the values in the 1st column <5.0


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in greater
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in less
  """Entry point for launching an IPython kernel.


array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

In [12]:
a2d_f[np.isnan(a2d_f)] = 0
#replace values nan with zero
a2d_f

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 0. , 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 0. , 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0. ],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0. ],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [13]:
uniqs, counts = np.unique(a2d_f, return_counts=True)
#Count all unique values in an array and print them together with the counted amount
uniqs, counts



(array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 1. , 1.1, 1.2, 1.3, 1.4, 1.5,
        1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8,
        2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4. , 4.1,
        4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1, 5.2, 5.3, 5.4,
        5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7,
        6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.6, 7.7, 7.9]),
 array([20,  6, 26,  7,  5,  1,  1,  8,  4,  7, 18, 19, 26, 11,  5, 12,  7,
         7,  6,  6, 12,  6, 11,  4,  9, 14, 10, 27, 12, 13,  7, 12,  8,  4,
         4,  7,  5,  5,  4,  5,  3,  8,  8,  7,  7,  9, 11, 14, 17,  6,  3,
         8, 10, 12, 11,  9,  5,  8,  7,  3, 10,  7,  4,  3, 10,  3,  5,  1,
         1,  3,  1,  1,  1,  2,  1], dtype=int64))

In [14]:
a2mas = np.split(a2d_f, 2, axis = 0)
#Split an array horizontally into 2 arrays
a2mas

[array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 0. , 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 0. , 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0. ],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0. ],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5

In [16]:
a2mas_1 = a2mas[0]
a2mas_1[a2mas_1[:,0].argsort()]
#Sort array by column 1 ascending 




array([[0. , 2.8, 4.6, 1.5],
       [0. , 2.8, 4. , 1.3],
       [4.3, 3. , 1.1, 0.1],
       [4.4, 2.9, 0. , 0.2],
       [4.4, 3. , 1.3, 0.2],
       [4.4, 3.2, 1.3, 0.2],
       [4.5, 2.3, 1.3, 0.3],
       [4.6, 3.6, 1. , 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [4.6, 3.4, 1.4, 0.3],
       [4.6, 3.1, 1.5, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.8, 3.1, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.3],
       [4.9, 3.1, 1.5, 0.1],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 3.1, 1.5, 0.1],
       [4.9, 3. , 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5. , 3.2, 1.2, 0. ],
       [5. , 3.5, 1.6, 0.6],
       [5. , 3.3, 1.4, 0.2],
       [5. , 2. , 3.5, 1. ],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5. , 3.5, 1.3, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.1, 3.8, 1.9, 0. ],
       [5.1, 3.4, 1.5, 0.2],
       [5.1, 3

In [17]:
a2mas_2 = a2mas[1]
a2mas_2[a2mas_2[:, 1].argsort()[::-1]]
#Sort array by column 1 descending


array([[7.7, 3.8, 6.7, 2.2],
       [7.9, 3.8, 0. , 2. ],
       [7.2, 3.6, 6.1, 2.5],
       [6. , 3.4, 4.5, 1.6],
       [0. , 3.4, 5.4, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.7, 3.3, 5.7, 2.1],
       [6.3, 3.3, 6. , 2.5],
       [6.9, 3.2, 5.7, 2.3],
       [6.5, 3.2, 5.1, 2. ],
       [6.8, 3.2, 5.9, 2.3],
       [7.2, 3.2, 6. , 1.8],
       [6.4, 3.2, 5.3, 2.3],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6.9, 3.1, 5.1, 2.3],
       [6.7, 3.1, 4.7, 1.5],
       [6.5, 3. , 5.5, 1.8],
       [5.9, 3. , 5.1, 1.8],
       [7.6, 3. , 6.6, 2.1],
       [6.5, 3. , 5.8, 2.2],
       [7.1, 3. , 5.9, 2.1],
       [6.1, 3. , 4.6, 1.4],
       [5.6, 3. , 4.1, 1.3],
       [5.4, 3. , 4.5, 1.5],
       [6.7, 3. , 5. , 1.7],
       [5.7, 3. , 4.2, 1.2],
       [6.8, 3. , 5.5, 2.1],
       [6.6, 3. , 4.4, 1.4],
       [7.2, 3. , 5.8, 1.6],
       [6.5, 3. , 5.2, 2. ],
       [6.7, 3. , 5.2, 2.3],
       [6. , 3. , 4.8, 1.8],
       [0. , 3

In [18]:
np.concatenate([a2mas_1, a2mas_2] , axis = 0)
#Glue both arrays

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 0. , 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 0. , 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0. ],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0. ],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [19]:
unique, counts = np.unique(a2d_f, return_counts=True)
a_sort = dict(zip(unique, counts))
#count unique values
a_sort


{0.0: 20,
 0.1: 6,
 0.2: 27,
 0.3: 6,
 0.4: 7,
 0.5: 1,
 0.6: 1,
 1.0: 7,
 1.1: 4,
 1.2: 7,
 1.3: 20,
 1.4: 19,
 1.5: 26,
 1.6: 10,
 1.7: 6,
 1.8: 11,
 1.9: 7,
 2.0: 7,
 2.1: 6,
 2.2: 6,
 2.3: 11,
 2.4: 6,
 2.5: 11,
 2.6: 5,
 2.7: 9,
 2.8: 14,
 2.9: 10,
 3.0: 25,
 3.1: 12,
 3.2: 13,
 3.3: 8,
 3.4: 10,
 3.5: 8,
 3.6: 4,
 3.7: 4,
 3.8: 7,
 3.9: 5,
 4.0: 6,
 4.1: 4,
 4.2: 5,
 4.3: 3,
 4.4: 8,
 4.5: 9,
 4.6: 7,
 4.7: 7,
 4.8: 9,
 4.9: 11,
 5.0: 14,
 5.1: 15,
 5.2: 6,
 5.3: 3,
 5.4: 8,
 5.5: 10,
 5.6: 11,
 5.7: 11,
 5.8: 10,
 5.9: 4,
 6.0: 6,
 6.1: 9,
 6.2: 4,
 6.3: 9,
 6.4: 7,
 6.5: 5,
 6.6: 3,
 6.7: 10,
 6.8: 3,
 6.9: 5,
 7.0: 1,
 7.1: 1,
 7.2: 3,
 7.3: 1,
 7.6: 1,
 7.7: 4,
 7.9: 1}

In [29]:
a2d_f[counts.max(),3]
#find the most duplicate number in an array

0.2

In [30]:
x = a2d_f[:,2].flatten() 
#third column
x


array([1.4, 1.4, 1.3, 1.5, 1.4, 0. , 1.4, 1.5, 0. , 1.5, 1.5, 1.6, 1.4,
       1.1, 1.2, 1.5, 1.3, 1.4, 1.7, 1.5, 1.7, 1.5, 1. , 1.7, 1.9, 1.6,
       1.6, 1.5, 1.4, 1.6, 1.6, 1.5, 1.5, 1.4, 1.5, 1.2, 0. , 1.5, 1.3,
       1.5, 1.3, 1.3, 1.3, 1.6, 1.9, 1.4, 1.6, 1.4, 1.5, 1.4, 4.7, 4.5,
       4.9, 4. , 4.6, 4.5, 4.7, 3.3, 4.6, 3.9, 3.5, 4.2, 4. , 4.7, 3.6,
       4.4, 4.5, 4.1, 4.5, 3.9, 4.8, 4. , 4.9, 4.7, 4.3, 4.4, 4.8, 5. ,
       0. , 3.5, 3.8, 3.7, 3.9, 5.1, 4.5, 4.5, 4.7, 4.4, 4.1, 0. , 4.4,
       4.6, 4. , 3.3, 4.2, 4.2, 4.2, 4.3, 3. , 4.1, 6. , 5.1, 5.9, 5.6,
       5.8, 6.6, 4.5, 6.3, 5.8, 6.1, 5.1, 5.3, 5.5, 5. , 5.1, 5.3, 5.5,
       6.7, 6.9, 5. , 5.7, 4.9, 6.7, 4.9, 5.7, 6. , 4.8, 4.9, 5.6, 5.8,
       6.1, 0. , 5.6, 5.1, 5.6, 0. , 5.6, 5.5, 4.8, 5.4, 5.6, 5.1, 5.1,
       5.9, 5.7, 5.2, 5. , 5.2, 5.4, 5.1])

In [31]:
def func(x):
    x = np.where(x < np.mean(x), x*2, x/4)
    return x
#a function that multiplies all values less than the average by 2 and divides the remaining values by 4
func(x)

array([2.8  , 2.8  , 2.6  , 3.   , 2.8  , 0.   , 2.8  , 3.   , 0.   ,
       3.   , 3.   , 3.2  , 2.8  , 2.2  , 2.4  , 3.   , 2.6  , 2.8  ,
       3.4  , 3.   , 3.4  , 3.   , 2.   , 3.4  , 3.8  , 3.2  , 3.2  ,
       3.   , 2.8  , 3.2  , 3.2  , 3.   , 3.   , 2.8  , 3.   , 2.4  ,
       0.   , 3.   , 2.6  , 3.   , 2.6  , 2.6  , 2.6  , 3.2  , 3.8  ,
       2.8  , 3.2  , 2.8  , 3.   , 2.8  , 1.175, 1.125, 1.225, 1.   ,
       1.15 , 1.125, 1.175, 6.6  , 1.15 , 0.975, 7.   , 1.05 , 1.   ,
       1.175, 0.9  , 1.1  , 1.125, 1.025, 1.125, 0.975, 1.2  , 1.   ,
       1.225, 1.175, 1.075, 1.1  , 1.2  , 1.25 , 0.   , 7.   , 0.95 ,
       0.925, 0.975, 1.275, 1.125, 1.125, 1.175, 1.1  , 1.025, 0.   ,
       1.1  , 1.15 , 1.   , 6.6  , 1.05 , 1.05 , 1.05 , 1.075, 6.   ,
       1.025, 1.5  , 1.275, 1.475, 1.4  , 1.45 , 1.65 , 1.125, 1.575,
       1.45 , 1.525, 1.275, 1.325, 1.375, 1.25 , 1.275, 1.325, 1.375,
       1.675, 1.725, 1.25 , 1.425, 1.225, 1.675, 1.225, 1.425, 1.5  ,
       1.2  , 1.225,